# Generated by Django 6.0.6 on 2026-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.CharField(help_text='A high-impact business value one-liner.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of deliverables.')),
                ('icon_type', models.CharField(choices=[('code', 'Web Development / Next.js / Django'), ('terminal', 'Automation & Scraping / Playwright'), ('cpu', 'AI Integration & Logic Trees')], default='code', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility on homepage.')),
                ('display_order', models.IntegerField(default=0, help_text='Controls sorting order.')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
