# Generated by Django 6.0.6 on 2026-06-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(max_length=100)),
                ('budget', models.CharField(blank=True, help_text='Estimated budget range', max_length=50, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New / Unread'), ('contacted', 'Contacted / In Progress'), ('closed', 'Closed / Won'), ('archived', 'Archived / Spam')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
