# Generated by Django 6.0.6 on 2026-06-08 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HunterSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('rank', models.CharField(choices=[('E', 'E-Rank Intern'), ('D', 'D-Rank Junior'), ('C', 'C-Rank Developer'), ('B', 'B-Rank Full-Stack'), ('A', 'A-Rank Elite Engineer'), ('S', 'S-Rank Monarch')], default='E', max_length=1)),
                ('strength', models.IntegerField(default=10, help_text='Backend (Django, PostgreSQL, SQL)')),
                ('agility', models.IntegerField(default=10, help_text='Frontend (React, Next.js, Tailwind)')),
                ('intelligence', models.IntegerField(default=10, help_text='AI/ML & Core Python')),
                ('sense', models.IntegerField(default=10, help_text='Debugging & System Architecture')),
                ('quest_code_committed', models.BooleanField(default=False)),
                ('quest_docs_read', models.BooleanField(default=False)),
                ('quest_logic_solved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
