# Generated by Django 6.0.6 on 2026-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_huntersystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('stat_category', models.CharField(choices=[('STR', 'Strength'), ('INT', 'Intelligence'), ('AGI', 'Agility'), ('WIS', 'Wisdom'), ('WIL', 'Willpower')], max_length=3)),
                ('xp_reward', models.IntegerField(default=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_logged', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Samuel James', max_length=50)),
                ('current_level', models.IntegerField(default=1)),
                ('total_xp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('willpower', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'User Status',
            },
        ),
    ]
